apiVersion: v1
kind: Service
metadata:
  name: rate-service
  namespace: currency-converter
  labels:
    app: rate-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: rate-service
  sessionAffinity: None
