# Rate Service - Staging Environment

logging.level.root=INFO
logging.level.com.example=DEBUG

exchange-rate.api.key={cipher}PLACEHOLDER_STAGING_EXCHANGE_RATE_KEY

security.api.key={cipher}PLACEHOLDER_STAGING_INTERNAL_API_KEY
