# Rate Service - Development Environment

logging.level.root=DEBUG
logging.level.com.example=TRACE

exchange-rate.api.key=dev-exchange-rate-api-key-plaintext

security.api.key=dev-internal-api-key-plaintext
