apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  template:
    spec:
      containers:
      - name: config-server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "768Mi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
