spring.cloud.config.server.git.uri=${CONFIG_REPO_URI}
spring.cloud.config.server.git.default-label=staging
spring.cloud.config.server.git.username=${CONFIG_REPO_USERNAME}
spring.cloud.config.server.git.password=${CONFIG_REPO_PASSWORD}

logging.level.root=INFO
logging.level.org.springframework.cloud.config=DEBUG
