spring.cloud.config.server.git.uri=${CONFIG_REPO_URI}
spring.cloud.config.server.git.default-label=staging
spring.cloud.config.server.git.username=${CONFIG_REPO_USERNAME}
spring.cloud.config.server.git.password=${CONFIG_REPO_PASSWORD}

# Keystore encryption (required in staging - no defaults)
encrypt.key-store.location=classpath:/${KEYSTORE_NAME}
encrypt.key-store.password=${KEYSTORE_PASSWORD}
encrypt.key-store.alias=${KEYSTORE_ALIAS}
encrypt.key-store.secret=${KEYSTORE_SECRET}

logging.level.root=INFO
logging.level.org.springframework.cloud.config=DEBUG
